import {
  Accessibility,
  Activity,
  Aperture,
  AppWindow,
  Atom,
  AtSign,
  AudioLines,
  Banana,
  Blocks,
  BookOpen,
  Bot,
  Braces,
  BrainCircuit,
  Briefcase,
  Bug,
  Camera,
  ChartColumn,
  ChartScatter,
  Clapperboard,
  ClipboardCheck,
  Cloud,
  Code,
  Container,
  Database,
  FileCode,
  FileCode2,
  Film,
  Frame,
  Gauge,
  Gem,
  GitBranch,
  GitPullRequest,
  GraduationCap,
  Handshake,
  Headset,
  HeartPulse,
  History,
  IdCard,
  Image as ImageIcon,
  Layers,
  LetterText,
  Lightbulb,
  Link2,
  Mail,
  Map as MapIcon,
  MessageCircle,
  MessageCircleQuestion,
  MessageSquare,
  Network,
  NotebookPen,
  Palette,
  PencilRuler,
  PenTool,
  Presentation,
  QrCode,
  Quote,
  Radar,
  Receipt,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  SquarePlay,
  SquareTerminal,
  Telescope,
  TestTube,
  Timer,
  TrendingUp,
  Type,
  Users,
  Video,
  Wand,
  Wrench,
  Zap,
} from 'lucide-react'
import type { ComponentType, SVGProps } from 'react'

/**
 * Registry entries name their icon as a string, so the registry stays a plain
 * data module with no React imports. This maps those names to components.
 *
 * Importing named icons individually (rather than the barrel) keeps the bundle
 * to only the icons actually used.
 *
 * Unknown names fall back to a wrench rather than throwing, so a typo in the
 * registry degrades visually instead of breaking the build. The registry test
 * asserts every referenced icon resolves, which is where a typo gets caught.
 */
const ICONS: Record<string, ComponentType<SVGProps<SVGSVGElement>>> = {
  Accessibility,
  Aperture,
  AppWindow,
  AtSign,
  Atom,
  AudioLines,
  Banana,
  Blocks,
  BookOpen,
  Bot,
  Braces,
  BrainCircuit,
  Briefcase,
  Bug,
  Camera,
  ChartColumn,
  Clapperboard,
  ClipboardCheck,
  Cloud,
  Code,
  Container,
  Database,
  FileCode,
  FileCode2,
  Film,
  Frame,
  Gauge,
  Gem,
  GitBranch,
  GitPullRequest,
  GraduationCap,
  Handshake,
  HeartPulse,
  Headset,
  History,
  IdCard,
  ImageIcon,
  Layers,
  LetterText,
  Lightbulb,
  Link2,
  Mail,
  MapIcon,
  MessageCircle,
  MessageCircleQuestion,
  MessageSquare,
  Network,
  NotebookPen,
  Activity,
  Palette,
  PencilRuler,
  PenTool,
  Presentation,
  QrCode,
  Quote,
  Radar,
  Receipt,
  Rocket,
  Scale,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  SquarePlay,
  SquareTerminal,
  Telescope,
  TestTube,
  Timer,
  TrendingUp,
  Type,
  Users,
  ChartScatter,
  Video,
  Wand,
  Wrench,
  Zap,
}

export function hasIcon(name: string): boolean {
  return name in ICONS
}

export function Icon({
  name,
  className,
  ...rest
}: { name: string; className?: string } & SVGProps<SVGSVGElement>) {
  const Cmp = ICONS[name] ?? Wrench
  return <Cmp className={className} aria-hidden="true" focusable="false" {...rest} />
}
